id: I8B072204
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:11:54+00:00'
last_modified: '2022-06-07T21:13:53.224377+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20329
  title: ཆོས་ལུགས་རིག་པའི་མདོ་དོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    D565:
      image_group_id: I8LS20331
      title: ''
      total_pages: 675
      order: 1
      base_file: D565.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
